In [36]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
df=pd.read_csv("https://raw.githubusercontent.com/NeilPandey/Test_Dataset/master/house_price.csv")

In [37]:
df.head()

Unnamed: 0      Location  BHK  Furnishing  Sq.ft  Old(years)  Floor  Price
0          37    Whitefield    3           1   3000           1      3  28000
1          43  Bommanahalli    3           1   1650          10      0  18000
2          12    Whitefield    2           0   1000           5      3  16400
3           8    Whitefield    3           0   1600           1      9  27000
4           9    Whitefield    2           1   1200           5      1  20000

In [38]:
df['Sq.ft'].value_counts().sort_values()

1050    13
1568    14
1375    15
1760    16
1471    16
1704    16
1333    17
1400    17
2292    17
1251    17
1768    18
1744    18
1326    18
2200    18
3155    18
1381    18
2117    19
1870    19
1675    20
1650    20
1033    21
2100    21
1245    21
1290    22
3000    22
960     22
1500    24
1200    24
2180    25
767     25
1135    27
1280    29
1088    29
1300    36
1460    36
1600    38
950     40
1250    43
1060    43
1000    47
1089    61
Name: Sq.ft, dtype: int64

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Unnamed: 0  1000 non-null   int64 
 1   Location    1000 non-null   object
 2   BHK         1000 non-null   int64 
 3   Furnishing  1000 non-null   int64 
 4   Sq.ft       1000 non-null   int64 
 5   Old(years)  1000 non-null   int64 
 6   Floor       1000 non-null   int64 
 7   Price       1000 non-null   int64 
dtypes: int64(7), object(1)
memory usage: 62.6+ KB


In [40]:
df.shape

(1000, 8)

In [41]:
df = df.drop(['Unnamed: 0'],axis=1)
df

Location  BHK  Furnishing  Sq.ft  Old(years)  Floor  Price
0      Whitefield    3           1   3000           1      3  28000
1    Bommanahalli    3           1   1650          10      0  18000
2      Whitefield    2           0   1000           5      3  16400
3      Whitefield    3           0   1600           1      9  27000
4      Whitefield    2           1   1200           5      1  20000
..            ...  ...         ...    ...         ...    ...    ...
995  Bommanahalli    3           1   1460           1      2  25000
996    Whitefield    3           0   2100           1      7  28000
997  Bommanahalli    2           0   1033           5      0  16500
998  Bommanahalli    3           0   1500          10      1  22000
999    Whitefield    3           1   1768           5     11  30000

[1000 rows x 7 columns]

In [42]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score
from sklearn.metrics import accuracy_score


In [43]:
label_enc = LabelEncoder()

In [44]:
# Data encoding
df['Location'] = label_enc.fit_transform(df['Location'])
df.head()

Location  BHK  Furnishing  Sq.ft  Old(years)  Floor  Price
0         1    3           1   3000           1      3  28000
1         0    3           1   1650          10      0  18000
2         1    2           0   1000           5      3  16400
3         1    3           0   1600           1      9  27000
4         1    2           1   1200           5      1  20000

In [45]:
X = df.drop('Price', axis=1)
y = df['Price']

In [46]:
X.head()

Location  BHK  Furnishing  Sq.ft  Old(years)  Floor
0         1    3           1   3000           1      3
1         0    3           1   1650          10      0
2         1    2           0   1000           5      3
3         1    3           0   1600           1      9
4         1    2           1   1200           5      1

In [47]:
y.head()

0    28000
1    18000
2    16400
3    27000
4    20000
Name: Price, dtype: int64

In [48]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.25)


In [49]:
X_train.head()

Location  BHK  Furnishing  Sq.ft  Old(years)  Floor
337         0    2           0   1050          10      2
906         0    3           1   3000           1      3
458         1    2           0   1290           1     10
849         0    2           1    767           1      3
945         1    2           0   1326           1      3

In [50]:
print("X_train dataset", len(X_train))
print("y_train dataset",len(y_train))

X_train dataset 750
y_train dataset 750


In [53]:
reg = LinearRegression()

In [54]:
reg.fit(X_train,y_train)


LinearRegression()

In [55]:
reg.coef_

array([3885.4911346 , 1800.24085411, 1274.98306999,    9.84763058,
        -22.46612482,  488.45198344])

In [56]:
reg.intercept_

340.18436511213804

In [57]:
X_test.head()

Location  BHK  Furnishing  Sq.ft  Old(years)  Floor
843         0    2           1    767           1      3
316         0    2           1   1089           5      2
642         0    3           0   1744           1      2
668         0    3           0   1500          10      1
190         1    3           0   2200           1     10

In [58]:
y_test.head()

843    16000
316    15500
642    22000
668    22000
190    42000
Name: Price, dtype: int64

In [59]:
y_pred = reg.predict(X_test)
y_pred

array([14211.67162322, 16804.29218706, 23869.61249996, 20776.14353176,
       36153.23904631, 19791.41408029, 14635.08613167, 22327.00518171,
       38001.67156111, 30557.14501761, 21784.14967577, 19116.67761283,
       18640.76698142, 32644.30572998, 15869.96949962, 25391.65436496,
       26698.82651462, 16804.29218706, 14000.93783773, 14000.93783773,
       15869.96949962, 28052.52109147, 33572.63319017, 21784.14967577,
       38001.67156111, 22742.44928184, 14635.08613167, 13672.03648309,
       24710.13178192, 23039.81920522, 15032.92090037, 22347.8684854 ,
       38001.67156111, 20776.14353176, 32028.4961952 , 23869.61249996,
       22347.8684854 , 21737.5617086 , 29756.20871523, 17613.07725437,
       17613.07725437, 38001.67156111, 41887.16269571, 33703.12003804,
       18516.43101029, 33572.63319017, 15032.92090037, 18516.43101029,
       18916.50063764, 16804.29218706, 21784.14967577, 14211.67162322,
       16804.29218706, 18730.6314807 , 36153.23904631, 41161.65839864,
      

In [60]:
reg.predict([[0,2,0,960,10,3]])

array([14635.08613167])

In [61]:
reg.predict([[1,3,0,2180,1,11]])

array([36444.73841817])

In [62]:
acc = (sum(y_pred)/sum(y_test))

In [63]:
import pickle as pk

In [65]:
with open ('C:/Users/shind/JupiterWorking/iNuron/EDA/BangaloreProperties/model.pkl','wb') as f:
    pk.dump(reg,f)

In [66]:
with open('C:/Users/shind/JupiterWorking/iNuron/EDA/BangaloreProperties/model.pkl','rb') as f:
    pk.load(f)