In [7]:
import pandas as pd
import numpy as np


In [2]:
# Use double backslashes or raw string to handle file path in Windows
file_path = r"D:\\MLProjects\\ZDatasets\\Quera Question Pair\\train01.xlsx"

# Read the Excel file into a pandas DataFrame
df = pd.read_excel(file_path)

# Display the DataFrame to verify it has been read correctly
print(df.head())  # or df to display the entire DataFrame


   id  qid1  qid2                                          question1  \
0   0     1     2  What is the step by step guide to invest in sh...   
1   1     3     4  What is the story of Kohinoor (Koh-i-Noor) Dia...   
2   2     5     6  How can I increase the speed of my internet co...   
3   3     7     8  Why am I mentally very lonely? How can I solve...   
4   4     9    10  Which one dissolve in water quikly sugar, salt...   

                                           question2  is_duplicate  
0  What is the step by step guide to invest in sh...             0  
1  What would happen if the Indian government sto...             0  
2  How can Internet speed be increased by hacking...             0  
3  Find the remainder when [math]23^{24}[/math] i...             0  
4            Which fish would survive in salt water?             0  


In [3]:
df.sample(10)


id    qid1    qid2  \
247226  247226  322829  260262   
320572  320572  446143  446144   
232957  232957  343078    2136   
2661      2661    5286    5287   
329290  329290   83053  341634   
227253  227253  336037  336038   
358946  358946  488509  255839   
265690  265690  382711  382712   
186934  186934  285019  285020   
261040  261040  377087  377088   

                                                question1  \
247226                       Why Adam D Angelo is stupid?   
320572             What is the meaning of actual poverty?   
232957  What is the sexiest thing you could observe/fi...   
2661             Where does the penis go when having sex?   
329290  Which intersections in London, ON are particul...   
227253  What makes a woman beautiful besides her physi...   
358946                  What is an example of a genotype?   
265690  What are the major differences in Wahhabism an...   
186934  What is the holiday schedule like in SRM, NCR,...   
261040  How does one decide on which kernel to choose ...   

                                                question2  is_duplicate  
247226                      Why is Adam D'Angelo so good?             0  
320572               What is the real meaning of poverty?             0  
232957    Do Indian girls use dildos? What kind of dildo?             0  
2661    What will a woman think of me if while having ...             0  
329290  Which intersections in Seattle are particularl...             0  
227253                          What makes her beautiful?             0  
358946              What are some examples of a genotype?             1  
265690  Is Wahhabism and Salafism the same in practica...             0  
186934  What is the holiday schedule like in SRM, Katt...             0  
261040  What is a typical training time for an SVM cla...             0

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 404290 entries, 0 to 404289
Data columns (total 6 columns):
 #   Column        Non-Null Count   Dtype 
---  ------        --------------   ----- 
 0   id            404290 non-null  int64 
 1   qid1          404290 non-null  int64 
 2   qid2          404290 non-null  int64 
 3   question1     404288 non-null  object
 4   question2     404287 non-null  object
 5   is_duplicate  404290 non-null  int64 
dtypes: int64(4), object(2)
memory usage: 18.5+ MB


In [4]:
ques_df = df.loc[:30000,['question1','question2']]
ques_df


question1  \
0      What is the step by step guide to invest in sh...   
1      What is the story of Kohinoor (Koh-i-Noor) Dia...   
2      How can I increase the speed of my internet co...   
3      Why am I mentally very lonely? How can I solve...   
4      Which one dissolve in water quikly sugar, salt...   
...                                                  ...   
29996  How do I break into a password user account on...   
29997  Why don't sourashtrians get married at early a...   
29998      Has there been a book that changed your life?   
29999                        What is Resource allocator?   
30000  I am in my late 20's and I look older than I a...   

                                               question2  
0      What is the step by step guide to invest in sh...  
1      What would happen if the Indian government sto...  
2      How can Internet speed be increased by hacking...  
3      Find the remainder when [math]23^{24}[/math] i...  
4                Which fish would survive in salt water?  
...                                                  ...  
29996  I forgot my Windows 10 admin password. How can...  
29997                        Find the factors of 3x^2+x?  
29998  What are the top-five books that changed your ...  
29999  What are optimal ratios for not for profit bud...  
30000                           Is domino's pizza halal?  

[30001 rows x 2 columns]

In [8]:
from sklearn.feature_extraction.text import CountVectorizer
# merge texts
questions = list(ques_df['question1'].astype('str')) + list(ques_df['question2'].astype('str'))

cv = CountVectorizer(max_features=3000)
X = cv.fit_transform(questions).toarray()
print(X)

q1_arr, q2_arr = np.vsplit(X,2)


[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [62]:
temp_df1 = pd.DataFrame(q1_arr, index= ques_df.index)
temp_df2 = pd.DataFrame(q2_arr, index= ques_df.index)
temp_df = pd.concat([temp_df1, temp_df2], axis=1)
temp_df.shape


(30001, 6000)

In [63]:
temp_df


0     1     2     3     4     5     6     7     8     ...  2991  2992  2993  2994  2995  2996  2997  2998  2999
0         0     0     0     0     0     0     0     0     0  ...     0     0     0     0     0     0     0     0     0
1         0     0     0     0     0     0     0     0     0  ...     0     0     0     0     0     0     0     0     0
2         0     0     0     0     0     0     0     0     0  ...     0     0     0     0     0     0     0     0     0
3         0     0     0     0     0     0     0     0     0  ...     0     0     0     0     0     0     0     0     0
4         0     0     0     0     0     0     0     0     0  ...     0     0     0     0     0     0     0     0     0
...     ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   ...   ...   ...   ...   ...   ...   ...   ...
29996     0     1     0     0     0     0     0     0     0  ...     0     0     0     0     0     0     0     0     0
29997     0     0     0     0     0     0     0     0     0  ...     0     0     0     0     0     0     0     0     0
29998     0     0     0     0     0     0     0     0     0  ...     0     1     0     0     0     0     0     0     0
29999     0     0     0     0     0     0     0     0     0  ...     0     0     0     0     0     0     0     0     0
30000     0     0     0     0     0     0     0     0     0  ...     0     0     0     0     0     0     0     0     0

[30001 rows x 6000 columns]

In [65]:
temp_df['is_duplicate'] = df['is_duplicate']
temp_df

0  1  2  3  4  5  6  7  8  9  10  ...  2990  2991  2992  2993  2994  2995  2996  2997  2998  2999  is_duplicate
0      0  0  0  0  0  0  0  0  0  0   0  ...     0     0     0     0     0     0     0     0     0     0             0
1      0  0  0  0  0  0  0  0  0  0   0  ...     0     0     0     0     0     0     0     0     0     0             0
2      0  0  0  0  0  0  0  0  0  0   0  ...     0     0     0     0     0     0     0     0     0     0             0
3      0  0  0  0  0  0  0  0  0  0   0  ...     0     0     0     0     0     0     0     0     0     0             0
4      0  0  0  0  0  0  0  0  0  0   0  ...     0     0     0     0     0     0     0     0     0     0             0
...   .. .. .. .. .. .. .. .. .. ..  ..  ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...           ...
29996  0  1  0  0  0  0  0  0  0  0   0  ...     0     0     0     0     0     0     0     0     0     0             0
29997  0  0  0  0  0  0  0  0  0  0   0  ...     0     0     0     0     0     0     0     0     0     0             0
29998  0  0  0  0  0  0  0  0  0  0   0  ...     0     0     1     0     0     0     0     0     0     0             0
29999  0  0  0  0  0  0  0  0  0  0   0  ...     0     0     0     0     0     0     0     0     0     0             0
30000  0  0  0  0  0  0  0  0  0  0   0  ...     0     0     0     0     0     0     0     0     0     0             0

[30001 rows x 6001 columns]

In [67]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(temp_df.iloc[:,0:-1].values,temp_df.iloc[:,-1].values,test_size=0.2,random_state=1)



In [68]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
rf = RandomForestClassifier()
rf.fit(X_train,y_train)
y_pred = rf.predict(X_test)
accuracy_score(y_test,y_pred)



0.7423762706215631

In [ ]:
from xgboost import XGBClassifier
xgb = XGBClassifier()
xgb.fit(X_train,y_train)
y_pred = xgb.predict(X_test)
accuracy_score(y_test,y_pred)